apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: review-services
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:   
    path: kubernetes-manifests/microservices-folders/reviews
    repoURL: https://github.com/Dezeabasili/microservices_kubernetes.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true