apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-reviews-volume
  labels: 
    app: mongodb-reviews
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /mnt/mongodb-reviews
  nodeAffinity:
    required: 
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker-01
