apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-auth
  template:
    metadata:
      labels:
        app: mongo-auth
    spec:
      nodeName: worker-01
      containers:
        - image: mongo
          name: mongo-auth
          args: ["--auth", "--dbpath", "/data/db"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth-secret
                  key: password
          volumeMounts:
            - mountPath: /data/db
              name: mongo-auth-volume
      volumes:
        - name: mongo-auth-volume
          persistentVolumeClaim:
            claimName: mongo-auth-pvc