apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app: hotels
    spec:
      # nodeName: worker-01
      containers:
        - image: doneze/hotelservices:1.0.18
          ports:
           - containerPort: 6000
          name: hotels
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-hotels-svc:27017/hotels"
            - name: RABBITMQ_URI
              value: "amqp://username:password@rabbitmq-service:5672"
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: access_token
                  name: access-token
            - name: REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: refresh_token
                  name: refresh-token
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  key: cloud_name
                  name: cloud-name
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: cloud_key
                  name: cloud-key
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  key: cloud_sec
                  name: cloud-sec
