---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: refresh-token
  namespace: default
spec:
  encryptedData:
    refresh_token: AgA46jAF3grw7grD+kpSUj6g5NSsHHu378OZ0JqSBY5vgskzV0/anLIXWJtpBhSTYXa3MjqnMC96IieH/3aRHgVmTQyLdjOVZ5cOoWuh6ENCcbx4w50qKp4EF2y8HUbIahbI/H8CjUUezxOX9716Ynt5S0delX6Az381zBgU4vYokjT3t6WpIKHjyb1IhcMx0hy08FTI0K4msCIGGsOPRj0Wm9JYtbUWbpVGrfAgZuBb5eRV1otQRtNbaTLRpQQR6l035LcHh0OZooxZTN8tLFzGDPCHhEKxXXvCIkMq9OOZ6K6AEw3j5lV5iCRsE2wsx6DEm8OSbkwZW4+30bp+/u7/6QW09UjOA2dmYfjxZp9yHloeQ5ns7BvfcQznjiNkCgC3WSl4MZ63JYpQfSnYRFywA+v2DN3bGmoNFElhN6dfOFimM9oY5dZW7DZwnDhKPMUFKwg5H4keR3OX5EM1BQT8HQWHfoyKsVeZsZBKzcR4wcHH4N3UPDJwnidDaidvqnW6g9WhHcUTqay8ee3QiTN/2uNK+vvqe1HertbCO1CKdbClM8T4xm35LhE2uqlOOzzJ9WKV9WjHmniQ0m3GLhrop3jAaOF9O6R7shzvJ6oiDBEBWOMcMER9Bzq+izR/18bLHaAGAgK8Xc7zMDSb2h5S/f0eVYtKWRuBpi76BkDE8BpGkRgs4c5VSSwwu/WXy5V6rWOMItThLr2lHPO5ygYZVKfn1uTn2UkHKAkLNZ0QjDZjKy8sjXrUts9k6TZ5LgeZCA7kclJNf7RpsoNetpCgY2/0K9nSLZ0QvsNwOSAuScVEK4Tex8KZhbuxLVrb5WwzroQsl4XnonsF4vCs78swv2oevUBaXMmPFM+ch2FiSQ==
  template:
    immutable: false
    metadata:
      creationTimestamp: null
      name: refresh-token
      namespace: default
    type: Opaque
